### ISSUE TITLE
Unable to fetch All Assets

### ISSUE THREAD

**Issue by RostislavLitovkin** [SubstrateGaming/Substrate.NET.API#44]
I am trying to fetch All Assets info from Astar parachain.

The endpoint I am using: wss://rpc.astar.network

I am calling assets.asset with

out any parameters. The result should look like this:

<img width="1511" alt="Screenshot 2023-05-06 at 12 08 05" src="https://user-images.githubusercontent.com/77352013/236618148-4a511b2c-7a4d-45e5-88a7-62579d08083f.png">

However when I try to fetch the data using the code bellow, I receive `null` instead of a string containing some data.

``` C#

 var str = await client.InvokeAsync<string>(
                            "state_getStorage",
                            new object[] { "0x682a59d51ab9e48a8c8cc418ff9708d2d34371a193a751eea5883e9553457b2e", null },
                            CancellationToken.None
                        );

// This is true
messagePopup.Text = (str == null).ToString();

```

**Comment by RostislavLitovkin** [comment]
Also, when I try to fetch the data with a parameter, for example like this, it does in-fact work:

``` C#
var str = await client.InvokeAsync<string>(
                            "state_getStorage",
                            new object[] { "0x682a59d51ab9e48a8c8cc418ff9708d2d34371a193a751eea5883e9553457b2ee7dafeb873ce4834a974435da87d9cc834050000000000000000000000000000", null },
                            CancellationToken.None
                        );

                        // This is false (As it should be)
                        messagePopup.Text = (str == null).ToString();
```

Hope this helps.

**Comment by darkfriend77** [comment]
@RostislavLitovkin let me help. Could you try to access the storage the way we do it in the generated SDKs, the NET API is a very primitive framework, it should be way easier to just use the generated Astar nuget package for accessing storage data.

In the link, you see how the access is built with the NET API.
Let me know if that works, or if there is an issue.

https://github.com/SubstrateGaming/Substrate.Chains.NET/blob/main/Substrate.Astar.NET/Substrate.Astar.NET.NetApiExt/NET/NetApiExt/Generated/Storage/MainAssets.cs

To catch all assets you will have to do multiple storage calls, query the keys and then query the storage to access all assets, in polkadot js this is hidden behind so it looks like one access.


something like this will query all the accounts and can be adapted to query all asset from star, let me know if that works.

```csharp
        public async Task<List<(string, AccountId32, AccountInfo)>> GetAccountsNextAsync(string startStorageKey, uint page, CancellationToken token)
        {
            if (!IsConnected)
            {
                return null;
            }

            if (page < 2 || page > 1000)
            {
                throw new NotSupportedException("Page size must be in the range of 2 - 1000");
            }

            var startKeyBytes = new byte[] { };
            if (startStorageKey != null)
            {
                startKeyBytes = Utils.HexToByteArray(startStorageKey);
            }

            var accountInfos = new List<(string, AccountId32, AccountInfo)>();
            var keyBytes = RequestGenerator.GetStorageKeyBytesHash("System", "Account");

            var storageKeys = await SubstrateClient.State.GetKeysPagedAsync(keyBytes, page, startKeyBytes, token);
            if (storageKeys == null || !storageKeys.Any())
            {
                return accountInfos;
            }

            var storageChangeSets = await SubstrateClient.State.GetQueryStorageAtAsync(storageKeys.Select(p => Utils.HexToByteArray(p.ToString())).ToList(), null, token);
            if (storageChangeSets != null)
            {
                foreach (var storageChangeSet in storageChangeSets.Changes)
                {
                    var storageKeyString = storageChangeSet[0];
                    var key = storageKeyString.Substring(storageKeyString.Length - 64);
                    var pubKey = Utils.HexToByteArray(key);

                    var accountId32 = new AccountId32();
                    accountId32.Create(pubKey);

                    var accountInfo = new AccountInfo();
                    accountInfo.Create(storageChangeSet[1]);

                    accountInfos.Add((storageKeyString, accountId32, accountInfo));
                }
            }

            return accountInfos;
        }

```

**Comment by darkfriend77** [comment]
Here is a test provided querying all, with a generic approach, might work for your purpose.

https://github.com/SubstrateGaming/Substrate.NET.API/blob/master/Substrate.NetApi.TestNode/QueryAllTest.cs

**Comment by RostislavLitovkin** [comment]
Thanks very much for help. I did not know I had to query it like this.

It took me some time, but I got it working ^^. Your example code did help a lot!

I have also made a PR with the fixes I had to make in order to make everything work. Go check them out :D.
