### ISSUE TITLE
Change the structure of Signing

### ISSUE THREAD

**Issue by RostislavLitovkin** [SubstrateGaming/Substrate.NET.API#55]
Right now, to sing a message, you need to write this:
```C#
byte[] signature;
switch (account.KeyType)
{
    case KeyType.Ed25519:
        signature = Ed25519.Sign(message, account.PrivateKey);
        break;

    case KeyType.Sr25519:
        signature = Sr25519v091.SignSimple(account.Bytes, account.PrivateKey, message);
        break;

    default:
        throw new Exception($"Unknown key type found '{account.KeyType}'.");
}
```

This always needs the exposure of the private key right in the code.

I propose a change to instead keep signing inside of an Account. It would work the same way as in polkadot.js api:
```js
// PRIVATE KEY TYPE + RAW SIGNATURE
const signature = alice.sign(message, { withType: true });
```

This could be done like this:
1) Create `IAccount` interface to allow foreign account formats to be used for signing. (This could be useful for a very elegant Plutonication integration)
```C#
public interface IAccount {
  ...Address
  ...KeyType
  ...Sign()
  ... more?
}
```

2) Implement `IAccount` for `Account` type.

3) Change the `public static UnCheckedExtrinsic SubmitExtrinsic(bool signed, Account account, Method method, Era era,
            uint nonce, ChargeType charge, Hash genesis, Hash startEra, RuntimeVersion runtime)` method to  support IAccount interface instead of Account type.

**Comment by RostislavLitovkin** [comment]
4) change the tests?

**Comment by darkfriend77** [comment]
Okay, yes let's see how feasable that is to implement.

**Comment by darkfriend77** [comment]
https://github.com/SubstrateGaming/Substrate.NET.API/pull/56

**Comment by darkfriend77** [comment]
Concerning 3. I'm not sure if having the interface makes sense, except if we would look for different account implementations. Or are there any specific thoughts behind this?

**Comment by RostislavLitovkin** [comment]
Yes, people would have the choice to use different account implementations.
They could for example use PlutonicationAccount instead, which would allow signing from a foreign wallet (Account) connected through Plutonication.

I can also imagine, that in the future, there would be other Account implementations as well.

One of them could be for example WalletConnect.
