### ISSUE TITLE
Add Value and Value2 in BaseEnumType

### ISSUE THREAD

**Issue by Apolixit** [SubstrateGaming/Substrate.NET.API#57]
Hey,

When we handle Events / Errors, we use BaseEnumExt<> generic class based on Enum index and generic parameter.
Here is the file : [BaseEnumExt](https://github.com/SubstrateGaming/Substrate.NET.API/blob/master/Substrate.NetApi/Model/Types/Base/BaseEnumExt.cs)

Each BaseEnumExt inherit from this mother class which is empty :
```c#
public abstract class BaseEnumType : BaseType
    {
    }
```

Value and Value2 properties are defined in each child class like this :

```c#
public class BaseEnumExt<T0, T1> : BaseEnumType
       where T0 : Enum
       where T1 : IType, new()
    {
        public override string TypeName() => typeof(T0).Name;

        // ...

        [JsonConverter(typeof(StringEnumConverter))]
        public T0 Value { get; set; }

        public IType Value2 { get; set; }
    }
```

Is there any way to put Value and Value2 in BaseEnumType ?
Of course for Value2 it is obvious, but Value can not be declare as :
```c#
public abstract class BaseEnumType : BaseType
    {
        public Enum Value { get; set; }
        public IType Value2 { get; set; }
    }
```

Currently, I have created an extension method in my project to handle this with reflexion:

```c#
public static class BaseEnumTypeExtension
    {
        public static Enum? GetValue(this BaseEnumType sender)
        {
            var prp = sender.GetType().GetProperty("Value");
            return (Enum?)prp?.GetValue(sender);
        }

        public static IType? GetValue2(this BaseEnumType sender)
        {
            var prp = sender.GetType().GetProperty("Value2");
            return (IType?)prp?.GetValue(sender);
        }

        public static T GetValue<T>(this BaseEnum<T> sender) where T : Enum
        {
            var prp = sender.GetType().GetProperty("Value");
            return (T)prp?.GetValue(sender);
        }
    }
```

But it seems not the best way to handle it.
@darkfriend77, @RostislavLitovkin  what do you think ? :)

**Comment by darkfriend77** [comment]
Should be possible to move them to the abstract type BaseEnumType, overall the BaseEnumExt seems one of the really bad workarounds for rust enumerations, that I would like to have solved in a different way.

**Comment by Apolixit** [comment]
Just move this issue to : #58
